import { Inter } from "next/font/google";
import '../globals.css'
import async from '../page';
import { connectDB } from "@/util/database";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
    const client = await connectDB;
    const db = client.db('forum')
    let result = await db.collection('post').find().toArray()

    return (
    // <html lang="en">
    //   <body className={inter.className}>
    //     <div className="detail-main">
          // <div className="list-bg-detail">
          //     {result.map((e,i)=>{
          //         return(
          //             <div className="list-item">
          //                 <a href={'/detail/'+e._id}><h4>{e.title}</h4></a>
          //                 <p>{e.content}</p>
          //             </div>
          //         )
          //     })}
          // </div>
    //     {children}
    //     </div>
        
    //     </body>
    // </html>
      <>
         <div className="list-bg-detail">
              {result.map((e,i)=>{
                  return(
                      <div className="list-item">
                          <a href={'/detail/'+e._id}><h4>{e.title}</h4></a>
                          <p>{e.content}</p>
                      </div>
                  )
              })}
          </div>
        {children}
      </>
    
  )
};
