import Link from "next/link";
import { Inter } from "next/font/google";
import "./globals.css";
import Loginbutton from "./loginbutton";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import { SessionProvider } from "next-auth/react";
import Logoutbutton from "./logoutbutton";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions)
  
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="navbar">
          <Link href="/" className="logo">Appleforum</Link> 
          <Link href="/list">List</Link> 
          
          {session ? <span>로그인됨{session.user.email}<Logoutbutton /></span> : <Loginbutton />}
        </div>
        
        {children}
        
        
      </body>
    </html>
  );
}
